Repository bptlab/blockchain-choreography, pull requests merged in 2018-12, with the labels that each got.

#13 Introduce roles to the choreography contract
  contracts/Arrays.sol
  contracts/Choreography.sol
  contracts/Migrations.sol
  contracts/Roles.sol
  migrations/2_deploy_contracts.js
  src/contract-interfaces/IChoreography.ts
Labels: feature, solidity

#16 Add modeler username and email address
  contracts/Choreography.sol
  contracts/Persons.sol
  contracts/Roles.sol
  src/contract-interfaces/IChoreography.ts
Labels: feature, solidity

#17 Feature - Card Components
  src/App.tsx
  src/components/ChangeCard.tsx
  src/components/MessageHistory.css
  src/components/MessageHistory.tsx
  src/components/StackedDate.css
  src/components/StackedDate.tsx
  src/components/StackedUser.css
  src/components/StackedUser.tsx
  src/contract-interfaces/IChoreography.ts
  src/index.css
  src/util/DateUtil.ts
  src/util/User.ts
  src/views/ChangeCard.css
  src/views/ChangeCard.tsx
  tsconfig.json
  tslint.json
  webpack.config.ts
Labels: feature, ui

#19 Use some default values when migrating / deploying the contracts
  migrations/2_deploy_contracts.js
Labels: solidity

#18 Write events to log
  contracts/Choreography.sol
Labels: feature, solidity

#22 Feature - Contract Interaction
  src/components/ButtonWidget.css
  src/components/ButtonWidget.tsx
  src/components/ContractInteractionWidget.css
  src/components/ContractInteractionWidget.tsx
  src/contract-interfaces/IChoreography.ts
  src/views/ChangeCard.css
  src/views/ChangeCard.tsx
Labels: feature, ui

#24 Add function to resolve a username to an address
  contracts/Choreography.sol
  contracts/Persons.sol
Labels: solidity

#25 Add the block timestamp to each event when emitting
  contracts/Choreography.sol
Labels: solidity
